spring.application.name: cryptoflow

spring.rabbitmq.host: ${RABBITMQ_HOST:localhost}
spring.rabbitmq.port: ${RABBITMQ_PORT:5672}
spring.rabbitmq.username: ${RABBITMQ_USER:guest}
spring.rabbitmq.password: ${RABBITMQ_PASSWORD:guest}

spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:cryptoflow}
spring.datasource.username: ${MYSQL_USER:cryptoflow}
spring.datasource.password: ${MYSQL_PASSWORD:cryptoflow}
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto: update